name: CI

on:
  push:
  pull_request:
    paths-ignore:
    - '**.md'
    - '**.yml'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - name: Lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.37
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - name: Test
      run: go test ./...
